[package]
name = "linked-list"
version = "0.1.0"
authors = ["Martin Atria Paublo <maratripa@gmail.com>"]
description = "Linked list with insertion"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
